version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "7447:5432"
    volumes:
      - postgres_ramos_uc_backend:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: server
      POSTGRES_PASSWORD: 20242023
      POSTGRES_DB: ramos-uc-nuevo
    networks:
      - app-network
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - SECRET_KEY=holaMundo
      - POSTGRES_USER=server
      - POSTGRES_PASSWORD=20242023
      - POSTGRES_DB=ramos-uc-nuevo
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    depends_on:
      - postgres
    networks:
      - app-network

volumes:
  postgres_ramos_uc_backend:
    driver: local

networks:
  app-network:
    driver: bridge
