version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "7447:5432"
    volumes:
      - postgres_ramos_uc_backend:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: server
      POSTGRES_PASSWORD: 20242023
      POSTGRES_DB: ramos-uc-nuevo

volumes:
  postgres_ramos_uc_backend:
    driver: local
