INSERT INTO Permission (name)
VALUES 
    ('CREATE_EDIT_OWN_REVIEW'),
    ('SUDO')
ON CONFLICT (name) DO NOTHING;

INSERT INTO Career (name)
VALUES 
    ('Actuación'), 
    ('Administración Pública'), 
    ('Agronomía e Ingeniería Forestal'), 
    ('Antropología – Arqueología'), 
    ('Arquitectura'), 
    ('Arte'), 
    ('Astronomía'), 
    ('Biología'), 
    ('Biología Marina'), 
    ('Bioquímica'), 
    ('Ciencia Política'), 
    ('College Artes y Humanidades'), 
    ('College Ciencias Naturales y Matemáticas'), 
    ('College Ciencias Sociales'), 
    ('Construcción Civil'), 
    ('Derecho'), 
    ('Diseño'), 
    ('Enfermería'), 
    ('Estadística'), 
    ('Filosofía'), 
    ('Física'), 
    ('Fonoaudiología'), 
    ('Geografía'), 
    ('Historia'), 
    ('Ingeniería'), 
    ('Ingeniería en Recursos Naturales'), 
    ('Ingeniería Comercial'), 
    ('Kinesiología'), 
    ('Letras Hispánicas'), 
    ('Letras Inglesas'), 
    ('Licenciatura en Ingeniería en Ciencia De Datos'), 
    ('Licenciatura en Ingeniería en Ciencia de la Computación'), 
    ('Licenciatura en Interpretación Musical'), 
    ('Matemática'), 
    ('Medicina'), 
    ('Medicina Veterinaria'), 
    ('Música'), 
    ('Nutrición y Dietética'), 
    ('Odontología'), 
    ('Pedagogía en Educación Especial'), 
    ('Pedagogía en Educación Física y Salud'), 
    ('Pedagogía en Educación Media en Ciencias Naturales y Biología'), 
    ('Pedagogía en Educación Media en Física'), 
    ('Pedagogía en Educación Media en Matemática'), 
    ('Pedagogía en Educación Media en Química'), 
    ('Pedagogía en Educación Parvularia'), 
    ('Pedagogía en Inglés'), 
    ('Pedagogía General Básica'), 
    ('Periodismo – Dirección Audiovisual – Publicidad'), 
    ('Psicología'), 
    ('Química'), 
    ('Química y Farmacia'), 
    ('Sociología'), 
    ('Teología'), 
    ('Terapia Ocupacional'), 
    ('Trabajo Social')
ON CONFLICT (name) DO NOTHING;
